@startuml
skinparam componentStyle uml2
skinparam packageStyle rectangle

title Component Diagram - Compiler Internals

file "SourceFile.zn" as source
file "Executable" as executable

package "Compiler" as Compiler {

    package "Front-End" {
        [Lexer]
        [Parser]
        [Semantic Analyzer]
        note bottom of [Parser] : Macro expansion\nhappens here
    }

    package "Middle-End" {
        [LLVM IR Emitter]
    }

    artifact "Abstract Syntax Tree\n(AST)" as AST
    artifact "Symbol Table" as ST
}

package "Back-End\n(Embedded libraries)" as Backend {
    [LLVM Core\n(Optimization & Codegen)] as LLVM
    [Linker LLD] as LLD
}

source              --> [Lexer]             : Raw string
[Lexer]             --> [Parser]            : Token stream
[Parser]            --> AST                 : Build nodes

AST                 --> [Semantic Analyzer] : Inspect nodes
[Semantic Analyzer] ..> ST                  : Resolve scopes & types
[Semantic Analyzer] --> [LLVM IR Emitter]   : Validated AST

[LLVM IR Emitter]   ..> ST                  : Read symbols & types
[LLVM IR Emitter]   --> LLVM                : Build module in memory\n(or emit .ll)
[LLVM IR Emitter]   --> LLD                 : Object file (.o / .obj)
LLD                 --> executable          : Link binary

@enduml
